"""UA training case study (LAB-TRAINING-CASES-01): uncertainty propagation.

Simulator-neutral, API-first uncertainty analysis training example. Each input
attribute is generated by its own sampler (Database.add_sampled_attribute) —
uniform, normal, or a discrete PMF — the simulator callable is evaluated on
every sampled row, and the output distribution is summarized (mean, standard
deviation, 5th/95th percentiles). Deterministic via a fixed numpy seed.

    python examples/ua_training_propagation.py [--n 2000]

Prints:
    TRAINING-UA-COMPLETE n=<n> mean=<...> std=<...> p5=<...> p95=<...>
"""

import argparse

import numpy as np

from labeeb import Database, normal_sample, uniform_sample


# ------------------------------------------------------------------ simulator

def simulate_response(inputs):
    """Simulator-neutral response.

    y = 2.0 * TEMP - 1.5 * FLOW + 3.0 + NOISE_TERM

    Linear in the inputs on purpose: the training UA can be validated against
    the analytic expectation E[y] = 2.0*E[TEMP] - 1.5*E[FLOW] + 3.0 + E[disc].
    """
    return (
        2.0 * inputs["TEMP"]
        - 1.5 * inputs["FLOW"]
        + 3.0
        + inputs["DISC"]
    )


# ------------------------------------------------------------------ workflow

def run_ua(n=2000, seed=20260903):
    """Sample per-attribute distributions, propagate, summarize.

    Returns a summary dict usable by tests and by the CLI.
    """
    if n < 1:
        raise ValueError("n must be >= 1")
    np.random.seed(seed)

    db = Database()
    # Each attribute uses an independent sampling strategy (row-aligned).
    db.add_sampled_attribute(
        "TEMP", lambda size: uniform_sample(540.0, 560.0, size), size=n,
        description="coolant inlet temperature [K]", unit="K",
    )
    db.add_sampled_attribute(
        "FLOW", lambda size: normal_sample(1400.0, 30.0, size), size=n,
        description="coolant mass flow [kg/s]", unit="kg/s",
    )
    # Discrete PMF over { -1, 0, +1 } via a seeded callable sampler. (For the
    # bus-style DiscreteSampling object, seed it the same way or accept its
    # own RNG — a callable keeps this example fully reproducible.)
    db.add_sampled_attribute(
        "DISC",
        lambda size: np.random.choice([-1.0, 0.0, 1.0], size=size, p=[0.25, 0.5, 0.25]),
        size=n, description="discrete PMF term", unit="-",
    )

    outputs = np.array([simulate_response(db.get_row(i)) for i in range(n)], dtype=float)
    return {
        "n": n,
        "mean": float(outputs.mean()),
        "std": float(outputs.std(ddof=1)),
        "p5": float(np.percentile(outputs, 5)),
        "p95": float(np.percentile(outputs, 95)),
        "min": float(outputs.min()),
        "max": float(outputs.max()),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--n", type=int, default=2000, help="sample size (default 2000)")
    args = parser.parse_args(argv)

    summary = run_ua(n=args.n)
    print(
        f"TRAINING-UA-COMPLETE n={summary['n']} mean={summary['mean']:.4f} "
        f"std={summary['std']:.4f} p5={summary['p5']:.4f} p95={summary['p95']:.4f}"
    )
    print(
        f"  expected mean = {2.0 * 550.0 - 1.5 * 1400.0 + 3.0 + 0.0:.4f} "
        f"(analytic check for a linear simulator)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
